implantação do navbar
alexscmachado/ecommerce_machado pull request #1
Opened 2023-04-25 22:22 UTC by alexscmachado

Foi criado o menu dentro da pasta components.

2023-04-27 12:06 UTC, angelarf requested changes
Oi Alex e Cíntia!

Fiz alguns comentários, qualquer dúvida podem me procurar!

2023-04-27 12:06 UTC, angelarf commented on src/App.js
> +// import NavBar from './components/navbar/NavBar.js';
Acho q esse comentário pode ser removido né? 😉

2023-04-27 12:06 UTC, angelarf commented on src/components/navbar/NavBar.js
> +        <navbar>
Acredito que aqui era para ser a tag `<nav>` do HTML, certo?

2023-04-27 12:06 UTC, angelarf commented on src/components/navbar/NavBarMenu.js
> +function  menu ( {categoria , link}){
💡 Dica: Uma boa prática é nomear os componentes com o mesmo nome que o arquivo. 
Então ou eu renomearia a função para `NavBarMenu` ou o arquivo para `Menu`. 
Ah, sempre que estamos criando um componente utilizamos a primeira letra maiúscula 😉

2023-04-27 12:06 UTC, angelarf commented on src/components/navbar/NavBarMenu.js
> +           <ul className="menuContens">
Uma outra observação, é que pelo q eu entendi esse componente está sendo utilizado para ser os itens do menu (`<li>`) e não uma lista inteira (`<ul>`). Semanticamente, o HTML gerado não faz muito sentido. Ele entende que cada item do menu é uma lista nova. 

<img width="426" alt="image" src="https://user-images.githubusercontent.com/11818829/234855991-bbde4c7e-8b01-4857-bed2-78d0903cc75a.png">

Uma solução é colocar todos os itens do menu aqui nesse componente e não repetir ele lá fora. Ou então, colocar o elemento `<ul>` lá no navbar e aqui ser um componente de NavBarMenuItem

2023-04-29 20:52 UTC, alexscmachado commented on src/App.js
> +// import NavBar from './components/navbar/NavBar.js';
ok.

2023-04-29 20:52 UTC, alexscmachado commented on src/components/navbar/NavBar.js
> +        <navbar>
ok

2023-04-29 20:54 UTC, alexscmachado commented on src/components/navbar/NavBarMenu.js
> +function  menu ( {categoria , link}){
Feito.

2023-04-29 21:15 UTC, alexscmachado commented on src/components/navbar/NavBarMenu.js
> +           <ul className="menuContens">
Feito. Acho que agora está certo.

2023-05-02 17:13 UTC, crisCintia commented
Desafio do Menu aprovado

2023-05-02 17:13 UTC, merged