Sincronizar counter
alexscmachado/ecommerce_machado pull request #11
Opened 2023-05-16 19:25 UTC by crisCintia

Nesse pull request criamos a sincronia do counter no ItemDetails - Desafio aula 9

2023-05-17 00:17 UTC, angelarf requested changes
Oi gente! Parabéns pela entrega!

Deixei alguns comentários! Infelizmente não consegui rodar local a aplicação por conta do problema com o arquivo `NavBar.css`. 

Depois que fizerem as atualizações posso olhar novamente 😉

2023-05-17 00:17 UTC, angelarf commented on src/styles/Navbar.css
Oi gente! Esse arquivo está duplicado, por favor, removam o que não estiver correto 😸 
Ele está fazendo baguncinha no git e eu não consigo rodar local a branch haha

2023-05-17 00:17 UTC, angelarf commented on src/styles/Navbar.css
Outra opção é renomear 😉

2023-05-17 00:17 UTC, angelarf commented on src/components/datails/ItemDetails.js
> +    const InputComponent = true ? CountItens : InputComponent;
Essa parte está correta? 
Da forma que está sempre irá mostrar o CountItens, fazendo com que essa validação seja desnecessária

2023-05-17 16:18 UTC, crisCintia commented on src/styles/Navbar.css
Oi Ângela, o arquivo duplicado renomeei para Navbar2.css para não confundir, por que o certo é o NavBar.css

2023-05-17 16:29 UTC, crisCintia commented on src/components/datails/ItemDetails.js
> +    const InputComponent = true ? CountItens : InputComponent;
Sim, vocês está correta, realmente não precisava da validação se irá mostrar o CountItens, já ajustei o código e deu certo :D

2023-05-18 22:51 UTC, angelarf approved these changes
Deixei mais dois comentários, mas o código e entrega estão aprovados!
Parabéns

2023-05-18 22:51 UTC, angelarf commented on src/components/datails/ItemDetails.js
> +    const naoAdicionado = true;
Essa variável, no próximo passo, deveria ser atualizada ao adicionar um item no carrinho né? 
Vou deixar esse comentário para vcs pensarem nisso depois 😉

2023-05-18 22:51 UTC, angelarf commented on src/components/datails/ItemDetails.js
> +                    clearInterval(ammount); setAmmount(1); alert(ammount + " Produto(s) adicionado ao carrinho")
Não entendi o uso do clearInterval aqui, ele serve para limpar algum "timer", caso o parametro passado não seja um "timer" ele não faz nada.

Link da documentação: https://developer.mozilla.org/en-US/docs/Web/API/clearInterval

2023-05-22 22:34 UTC, merged