Criação CartContext
alexscmachado/ecommerce_machado pull request #12
Opened 2023-05-18 19:36 UTC by crisCintia

2023-05-24 00:06 UTC, angelarf requested changes
Oi gente! Deixei alguns comentários.. estou a disposição para ajudá-los 😸

2023-05-24 00:06 UTC, angelarf commented on package.json
> -    "react-icons": "^4.8.0",
Acredito que essas duas libs (react-icons e react-router-dom) são necessárias e não deveriam ser removidas. Certo?

2023-05-24 00:06 UTC, angelarf commented on src/components/navbar/NavBarCarrinho.js
> +export function Carrinho() {
É uma boa prática que cada componente tenha seu próprio arquivo. Isso ajuda na organização :D

2023-05-24 00:06 UTC, angelarf commented on src/components/navbar/NavBarCarrinho.js
> +    valor.itens.forEach(p => qdtProdutos += p.ammount);
Essa variável `ammount` não existe no objeto dentro do array de `itens`.

Creio que o ideal seria usar a função que você criou no context e não refazer a lógica nesse componente.
Ficaria assim:

```
const qtdProdutos = valor?.getItemQtd() || 0
 ``` 
 Obs: Adicionei o `|| 0` pois se a função não retornar nada, o valor será 0.

2023-05-24 00:06 UTC, angelarf commented on src/components/navbar/NavBarCarrinho.js
> +    valor.itens.forEach(p => qdtProdutos += p.ammount);
Imagem do erro que isso causou: 
![image](https://github.com/alexscmachado/ecommerce_machado/assets/11818829/a815d60b-e3e0-4b97-91a1-9f9a1a5bf8fb)

2023-05-24 00:06 UTC, angelarf commented on src/components/navbar/NavBarCarrinho.js
> +                {itens.map(p => <li key={p.id}>p.ammount</li>)}
Aqui tenho duas observações e uma sugestão:
1. A variável ammount não existe dentro dos objetos do array de itens, creio que você queira dizer qtd.
2. Para exibir o valor da variável, precisamos colocá-la entre chaves;
3. (Sugestão) Exibir também alguma informação que identifique o produto (nome ou id), isso ajuda o user a entender a informação. Como por hora vocês só armazenam o id, pode ser ele, mas pensem com carinho sobre mostrar o nome também (fica o desafio 😉 )


Exemplo de como ficaria com esses pontos alterados:
```
{itens.map(p => <li key={p.id}>Produto: {p?.id} - Qtd: {p.qtd}</li>)}
```

2023-05-24 00:06 UTC, angelarf commented on src/components/navbar/NavBarCarrinho.js
> +    const {itens, getItemQtd, clear, removeCart} = useCartContext();
Muito legal vcs terem usado dessa forma ❤️

2023-05-24 00:06 UTC, angelarf commented on src/contexts/CartContext.js
> +    function addToCart(id){
Para adicionar no carrinho, é necessário receber o id e a qtd. 
Percebi que você até passou a quantidade, mas executando temos erros lógicos. Então sugiro que vocês recebam aqui a quantidade como um parametro tbm.

Dessa forma:
```
function addToCart(id, qtd) {
```

2023-05-24 00:06 UTC, angelarf commented on src/contexts/CartContext.js
> +            cartItens.push({id:id, qtd:1});
Aqui a qtd a ser adicionada deveria ser a que recebeu na função. 
Por exemplo, eu como compradora vou comprar 2 batons .. então aqui eu deveria adicionar no array o objeto {id: id, qtd: 2}...

Então aqui ficaria assim:
``` 
cartItens.push({id:id, qtd:qtd})
```

2023-05-24 00:06 UTC, angelarf commented on src/contexts/CartContext.js
> +            cartValid.qtd = parseInt(cartValid.qtd + 1);
`cartValid.qtd = parseInt(cartValid.qtd + qtd);`

Aqui também precisamos atualizar para receber a quantidade correta 😉

2023-05-24 00:06 UTC, angelarf commented on src/components/datails/ItemDetails.js
> +                <CartContextProvider><button className="buyButton btn btn-primary" onClick={() => {
O` CartContextProvider` não é necessário aqui pq ele já está englobando todos os componentes lá no App.js.

2023-05-24 00:06 UTC, angelarf commented on src/components/datails/ItemDetails.js
> +                    clearInterval(ammount); setAmmount(1); addToCart(cardItem.id, cardItem.qtd); alert(ammount + " Produto(s) adicionado ao carrinho")
Algumas observações:
2. A função `clearInterval(ammount)` não faz sentido aqui, pois o `ammount` não é um timer
3. O parametro passado como qtd na função de addToCart deveria ser o `ammount` e não o `cardItem.qtd`:
```
<button
     className="buyButton btn btn-primary"
     onClick={() => {
         setAmmount(1);
         addToCart(cardItem.id, ammount);
         alert(ammount + " Produto(s) adicionado ao carrinho")
     }}>
        Adicionar ao carrinho
</button>
```

2023-05-24 00:06 UTC, angelarf commented on src/components/datails/ItemDetails.js
> +    const naoAdicionado = true;
Essa variável deveria vir do carrinho! Sugestão de refatoração:
1. no arquivo `CartContext` adicionar a função:
```
    const isInTheCart = (id) => itens.find(i => i.id === id);
```
Essa função é responsável por dizer se o item já existe no array dado um id;
Não esqueça de retornar ele para o Provider:
```
return (
        <CartContext.Provider value={{ itens, clear, getItemQtd, addToCart, removeCart, isInTheCart }}>
            {children}
        </CartContext.Provider>
    )
}
```

2. Nesse arquivo, refatore: Não precisa deixar fixo o valor true, utilize o valor vindo do context:
```
    const { addToCart, isInTheCart } = useCartContext();
    const naoAdicionado = !isInTheCart(cardItem.id);
```

2023-05-24 00:06 UTC, angelarf commented on src/components/navbar/NavBarCarrinho.js
> +            <button className="buyButton btn btn-primary" onClick={() => removeCart()}>Remover Item</button>
Aqui para que sua função de removeCart() faça sentido, seria necessário passar o id que será removido. 
Porém a proposta da página parece que você quer remover todos. 
Consegue me explicar qual o resultado esperado desse botão para que eu consiga te ajudar a fazer funcionar?
Obrigada!

2023-05-24 00:06 UTC, angelarf commented on src/components/navbar/NavBarCarrinho.js
> +            <button className="buyButton btn btn-primary" onClick={() => removeCart()}>Remover Item</button>
Relendo aqui, acho que o botão de remover item deveria estar ali dentro do map pq cada item precisa de um..
Sugestão:
```
itens.map(p => <li key={p.id}>
     <p>Produto: {p?.id} - Qtd: {p.qtd}</p>
     <button className="buyButton btn btn-primary" onClick={() => removeCart(p.id)}>Remover Item</button>
 </li>)}
```

2023-05-24 00:06 UTC, angelarf commented on src/contexts/CartContext.js
> +            setItens(cartValid);
Aqui nós temos um problema, pq na verdade o itens deveria ser um array, e ao fazer `setItens(cartValid)` você está substituindo tooodos os itens por esse aqui.

Ideia: 
 Precisamos atualizar o array de itens para que somente esse item tenha sua quantidade alterada. Minha sugestão é recriar o array com o uso do map. Vou colocar a ideia de refatoração para esse if:
 ```
 if (cartValid.qtd > 1) {
          const updatedArray = cartItens.map(item => {
                // verificamos se o item é o que queremos atualizar
                if (item?.id === id) {
                    //se for, calculamos a nova quantidade:
                    cartValid.qtd = parseInt(cartValid.qtd - 1);
                    // retornamos o objeto modificado:
                    return cartValid;
                }
                //Caso não seja o item que queremos modificar, retornamos o item sem modificações:
                return item;

            });
            // Atualizamos o array de itens
            setItens(updatedArray);
        } else {
            const arrayFilter = cartItens.filter(product => product.id !== id);
            setItens(arrayFilter);
        }   
```

2023-05-29 16:48 UTC, angelarf commented on src/contexts/CartContext.js
> +       }
Aqui vocês esqueceram de colocar uma ` }`. E ao rodar o programa dá erro.

2023-05-29 16:48 UTC, angelarf commented on src/components/navbar/NavBarCarrinho.js
> +            <div className="carrinho">{qdtProdutos}</div>
Typo: `qtdProdutos`  ao invés de `qdtProdutos`

2023-05-29 16:48 UTC, angelarf commented on src/components/navbar/NavBarCarrinho.js
>              <button className="buyButton btn btn-primary" onClick={() => removeCart()}>Remover Item</button>
Dica: Agora que você adicionou o botão de remover item ao lado do item, esse aqui não é necessário
<img width="652" alt="image" src="https://github.com/alexscmachado/ecommerce_machado/assets/11818829/ec4e8456-a2fa-4cb5-aced-0c1f77cb17f2">

2023-05-29 16:49 UTC, angelarf commented
Oi meninos! Vou considerar o desafio aprovado, já que a maioria dos pontos foram alterados, masss se sobrar dúvidas ou problemas, me chamem no chat da plataforma e eu posso ajudá-los :D 

Parabéns pela evolução

2023-05-29 16:49 UTC, angelarf approved these changes

2023-05-30 14:43 UTC, crisCintia commented
Desafio aprovado

2023-05-30 14:43 UTC, merged