ItemCollection
alexscmachado/ecommerce_machado pull request #18
Opened 2023-05-25 23:40 UTC by crisCintia

Resolução do desafio ItemCollection da aula e Firebase I.

2023-06-01 18:24 UTC, angelarf requested changes
Oie, deixei alguns comentários. 
Espero que ajude, caso ainda tenha dúvidas, pode me chamar

2023-06-01 18:24 UTC, angelarf commented on src/styles/Navbar.css
Oi Cinitia! Tudo bem?

Novamente tive problemas com esse arquivo, dei uma olhada no git de vocês e ele está duplicado.
Tente renomear o correto e remover o que não fizer sentido :)

2023-06-01 18:24 UTC, angelarf commented on src/styles/CartPage.css
Se esse arquivo estiver realmente vazio, sugiro que ele seja removido

2023-06-01 18:24 UTC, angelarf commented on src/contexts/UserContext.js
Como esse arquivo é o UserContext, sugiro que as funções e constantes dentro dele sigam o mesmo padrão de nomenclatura.
Ex:
```
cartContextProduct -> userContext
``` 
Ou então que renomeie o arquivo, para que as coisas se encaixem 😺

2023-06-01 18:24 UTC, angelarf commented on src/contexts/CartContext.js
> +//const carrinho = useContext(ItemDetails)
Pensando em deixar o código mais limpo, sugiro dar uma olhada no que desses comentários pode ser removido e apagar :)

2023-06-01 18:24 UTC, angelarf commented on src/components/datails/ItemDetailsContainer.js
> +    })
Se você não colocar um critério para o useEffect atualizar (ex: primeiro render, quando uma prop mudar)...  ele vai ser executado todo render e isso pode causar problemas de memória e até travar o acesso ao firebase, já q a conta gratuita tem limite de requests

2023-06-01 18:24 UTC, angelarf commented on src/components/datails/ItemDetailsContainer.js
> +        getDocs(CardCollection).then((snapshot) => {
Para pegar os detalhes de apenas um item, vocês poderiam usar a função getDoc do firebase.
https://firebase.google.com/docs/firestore/query-data/get-data#get_a_document

Seu código final ficaria parecido com esse:

```jsx

function ItemDetailsContainer() {
  const [loading, setLoading] = useState(true)
  const { itemId } = useParams()

  const [ProdDetail, setProdDetail] = useState([])

  const getDataFromFirebase = async () => {
    // Documentação sobre como pegar um documento específico no firebase:
    // https://firebase.google.com/docs/firestore/query-data/get-data#get_a_document
    const db = getFirestore()
    const docRef = doc(db, "item", `${itemId}`)
    const docSnap = await getDoc(docRef)

    if (docSnap.exists()) {
      setProdDetail({ ...docSnap.data(), id: itemId })
      setLoading(false)
    }
  }

  useEffect(() => {
    getDataFromFirebase()
  }, [itemId])

  if (loading) {
    return (
      <div
        className="spinner-grow text-secondary spinnerListItens"
        role="status"
      >
        <span className="visually-hidden">Loading...</span>
      </div>
    )
  }
  return (
    <div>
      <ItemDetails cardItem={ProdDetail} />
    </div>
  )
}
```

2023-06-01 18:24 UTC, angelarf commented on src/components/listItens/ListItensContents.js
> +    setTimeout(() => {
Esse setTimeout não é mais necessário. Pode ser removido

2023-06-01 18:24 UTC, angelarf commented on src/components/listItens/ListItensContents.js
>      useEffect(
Esse useEffect não é mais necessário, pode ser removido

2023-06-01 18:24 UTC, angelarf commented on src/components/listItens/ListItensContents.js
> +            setProdsCol(myProducts);
Não esqueça de colocar o loading como false aqui:
```
setLoading(false)
```

2023-06-01 18:24 UTC, angelarf commented on src/components/listItens/ListItensContents.js
>      useEffect(
Para o filtro por categorias funcionar, vc vai precisar mudar esse useEffect aqui tbm.

Ficará parecido com isso:
```

  useEffect(() => {
    if (categoryId) {
      const result = prodsCol.filter((p) => p.categoryId === categoryId)
      setFilteredProducts(result)
    }
  }, [categoryId, prodsCol])
  ```

2023-06-01 18:24 UTC, angelarf commented on src/components/listItens/ListItensContents.js
> +           <ListItens itens={prodsCol} /> {/*Essa é a aplicação com Firebase*/}
Continuando a alteração para fazer o filtro funcionar:

Validar se existir uma categoryId e retornar os itens filtrados, caso contrário retornar todos.

Pode ser feito algo parecido com isso:
```
return (
    <div className="itemContainerList">
      <ListItens itens={categoryId ? filteredProducts : prodsCol} />
    </div>
  )
  ```

2023-06-01 18:24 UTC, angelarf commented on src/components/listItens/ListItensContents.js
> +    useEffect( () => {
Remover comentários que não serão mais utilizados

2023-06-01 18:24 UTC, angelarf commented on src/components/datails/ItemDetails.js
> +                        addToCart(cardItem.id, ammount);
Como agora removemos o mock e queremos evitar mais uma consulta ao firestore, que tal passar o item completo?

Algo assim: 
```js
addToCart(cardItem, ammount)
```

2023-06-01 18:24 UTC, angelarf commented on src/components/datails/ItemDetails.js
> +    /*function addCart(qtd) {
Remover código nao utilizado

2023-06-01 18:24 UTC, angelarf commented on src/components/cart/CartPage.js
> +    function getProductsDetails() {
Essa função não é necessária

2023-06-01 18:24 UTC, angelarf commented on src/components/cart/CartPage.js
> +function Carrinho(cardItem) {
Esse parâmetro não é necessário mais pq pegamos os itens do contexto

2023-06-01 18:24 UTC, angelarf commented on src/components/cart/CartPage.js
> +    const [loading, setLoading] = useState(true);
não é mais necessário o loading

2023-06-01 18:24 UTC, angelarf commented on src/components/cart/CartPage.js
> +    const { itemId } = useParams();
esse parametro não existe nessa rota e não é necessário

2023-06-01 18:24 UTC, angelarf commented on src/components/cart/CartPage.js
> +        <div>
Aqui só precisa um pouco de organização para q os itens sejam exibidos corretamente. Removi os códigos que considerei não fazer mais sentido e ficou tipo assim:

```jsx

  return (
    <div>
      <ul>
        {itens.map((p) => (
          <CartItem key={p.id} cardItem={p} />
        ))}
      </ul>
      <p></p>
      <Link>
        <button className="buyButton btn btn-primary" onClick={() => clear()}>
          Esvaziar o Carrinho
        </button>
      </Link>
    </div>
  )
  ```

2023-06-01 18:24 UTC, angelarf commented on src/components/cart/Cart.js
> +    const { itens, setItens, getItemQtd, clear, removeCart, sumTotal } = useCartContext();
Como esse componente é de exibição de um item do carrinho, aconselho trabalhar apenas com o dado recebido por prop: `cardItem` .. Passado pelo pai em `CartPage.js`.

2023-06-01 18:24 UTC, angelarf commented on src/components/cart/Cart.js
> +    const { itens, setItens, getItemQtd, clear, removeCart, sumTotal } = useCartContext();
Então aqui ficaram assim:
```jsx
  const { getItemQtd, removeCart, sumTotal } = useCartContext()
```

2023-06-01 18:24 UTC, angelarf commented on src/components/cart/Cart.js
> +    const [ammount, setAmmount] = useState(1);
Pode remover esse state

2023-06-01 18:24 UTC, angelarf commented on src/components/cart/Cart.js
> +    function ClickOnChangeQtd(qtd) {
Essa função não é usada, pode ser removida

2023-06-01 18:24 UTC, angelarf commented on src/components/cart/Cart.js
> +    function getProductsDetails() {
essa função tbm não é usada e pode ser removida

2023-06-01 18:24 UTC, angelarf commented on src/components/cart/Cart.js
> +                <img src={itens.imagem} className=" cardDetailsImage" alt="Laptop" />
ao invés de pegar de itens.image, será necessário pegar o dado de `cardItem.image`
Ficará parecido com isso:
```jsx
return (
    <div className="container  cardDetailsContainer">
      <div className="cardDetailImageContent">
        <img
          src={cardItem?.imagem}
          className=" cardDetailsImage"
          alt="Laptop"
        />
      </div>
      <div className="cardDetailsItensContent">
        <p>{cardItem?.nome}</p>
        <p className=" CardDetailsNome ">R$ {cardItem?.preco}</p>
        <p>Quantidade: {getItemQtd()}</p>
        <p>Valor Total: R$ {sumTotal}</p>
        <button
          className="buyButton btn btn-primary"
          onClick={() => removeCart(cardItem?.id)}
        >
          Remover Item
        </button>
      </div>
    </div>
  )
  ```

2023-06-01 18:31 UTC, angelarf commented on src/components/listItens/ListItensContents.js
> +    setTimeout(() => {
Esse useEffect ficaria assim:
```jsx
  useEffect(() => {
    const db = getFirestore()

    const ItemCollection = collection(db, "item")
    getDocs(ItemCollection).then((snapshot) => {
      if (snapshot.size > 0) {
        const myProducts = snapshot.docs.map((prod) => ({
          id: prod.id,
          ...prod.data(),
        }))
        setProdsCol(myProducts)
        setLoading(false)
      }
    })
  }, [])
  ```

2023-06-06 16:23 UTC, crisCintia commented on src/styles/Navbar.css
Oi @angelarf tudo bem e vc? Ain, agora consegui excluir, eu tava procurando onde excluir e não achava, mas deu certo, agora só tem um arquivo NavBar.css, em todas as branchs :D

2023-06-06 16:24 UTC, crisCintia commented on src/styles/CartPage.css
Ahh no desafio do Item Collection 2 consegui adicionar a function Carrinho que estava no arquivo NavBar Carrinho, pq lá estava com duas function.

2023-06-06 16:28 UTC, crisCintia commented on src/contexts/UserContext.js
Beleza, podexá

2023-06-06 16:29 UTC, crisCintia commented on src/contexts/CartContext.js
> +//const carrinho = useContext(ItemDetails)
Beleza, acho que vou apagar os comentários, pq são dos outros desafios que atualizamos conforme foi passando as aulas e os novos desafios. E como está comentado, não está impactando o código

2023-06-06 18:29 UTC, crisCintia commented on src/components/datails/ItemDetailsContainer.js
> +        getDocs(CardCollection).then((snapshot) => {
Ahhh entendi, obrigada

2023-06-06 18:48 UTC, crisCintia commented on src/components/listItens/ListItensContents.js
>      useEffect(
Beleza, combinado

2023-06-06 18:49 UTC, crisCintia commented on src/components/listItens/ListItensContents.js
> +    setTimeout(() => {
Obrigada

2023-06-06 18:54 UTC, crisCintia commented on src/components/listItens/ListItensContents.js
> +            setProdsCol(myProducts);
Ah beleza, já coloquei como false, tinha deixado sem nada hehe

2023-06-06 19:00 UTC, crisCintia commented on src/components/listItens/ListItensContents.js
>      useEffect(
Ahh ficou melhor assim, obrigadaa

2023-06-06 19:00 UTC, crisCintia commented on src/components/listItens/ListItensContents.js
> +           <ListItens itens={prodsCol} /> {/*Essa é a aplicação com Firebase*/}
Belezaaa

2023-06-06 19:00 UTC, crisCintia commented on src/components/listItens/ListItensContents.js
> +    useEffect( () => {
Já removi os comentários dos outros arquivos tbm, para deixar mais limpo, obrigada

2023-06-06 19:03 UTC, crisCintia commented on src/components/datails/ItemDetails.js
> +    /*function addCart(qtd) {
Belezaa

2023-06-06 19:03 UTC, crisCintia commented on src/components/datails/ItemDetails.js
> +                        addToCart(cardItem.id, ammount);
Aí nesse caso, todas as informações do item vai para o carrinho de compras né?

2023-06-06 19:04 UTC, crisCintia commented on src/components/cart/CartPage.js
> +    function getProductsDetails() {
Beleza, quando fiz o desafio do Item Collection 2 conseguimos remover :D

2023-06-06 19:06 UTC, crisCintia commented on src/components/cart/CartPage.js
> +function Carrinho(cardItem) {
Beleza

2023-06-06 19:07 UTC, crisCintia commented on src/components/cart/CartPage.js
> +    const [loading, setLoading] = useState(true);
Beleza, no desafio do Item Collection 2 conseguimos removar o loading

2023-06-06 19:07 UTC, crisCintia commented on src/components/cart/CartPage.js
> +    const { itemId } = useParams();
Belezaa

2023-06-06 19:09 UTC, crisCintia commented on src/components/cart/CartPage.js
> +        <div>
Ahh obrigadaaa

2023-06-06 19:11 UTC, crisCintia commented on src/components/cart/Cart.js
> +    const [ammount, setAmmount] = useState(1);
Belezaa

2023-06-06 19:11 UTC, crisCintia commented on src/components/cart/Cart.js
> +    function ClickOnChangeQtd(qtd) {
Belezaa

2023-06-06 19:12 UTC, crisCintia commented on src/components/cart/Cart.js
> +    const { itens, setItens, getItemQtd, clear, removeCart, sumTotal } = useCartContext();
Belezaa, obrigadaa

2023-06-06 19:12 UTC, crisCintia commented on src/components/cart/Cart.js
> +    function getProductsDetails() {
Belezaa

2023-06-06 19:18 UTC, crisCintia commented on src/components/cart/Cart.js
> +                <img src={itens.imagem} className=" cardDetailsImage" alt="Laptop" />
@angelarf troquei o "itens.image" para o "cardItem?.imagem" só que a imagem ainda não aparece, vou tentar procurar melhor onde to errando. 
uma dúvida, no firebase coloquei a imagem como um link, so tipo string, será que pode ser isso? Por que o nome tbm está em string e não aparece tbm.

2023-06-06 20:22 UTC, crisCintia commented on src/components/datails/ItemDetailsContainer.js
> +    })
@angelarf só fiquei com dúvida nessa parte, vou tentar fazer e depois mostro como ficou :D

2023-06-06 20:24 UTC, crisCintia commented
@angelarf já fizemos as atualizações dessa pull request, deu tudo certo, muito obrigada pela ajudaa :D

2023-06-07 00:09 UTC, crisCintia commented on src/components/cart/Cart.js
> +                <img src={itens.imagem} className=" cardDetailsImage" alt="Laptop" />
@angelarf consegui ajustar para aparecer a imagem, você tinha comentado no outro pull request heheh

2023-06-12 14:20 UTC, merged