Item Collection 2
alexscmachado/ecommerce_machado pull request #20
Opened 2023-05-31 00:42 UTC by crisCintia

Pull request criada para o Desafio Item Collection 2 da aula de Firebase II.

Ângela, só ficamos com dúvida sobre esse erro, pois criamos o comando para salvar a coleção de ordem, mas não foi: 
![image](https://github.com/alexscmachado/ecommerce_machado/assets/111471174/b7758b42-7866-434d-99f4-03ecb6ca8ba7)

Do resto, conseguimos adicionar o preço e o valor total do item e da compra no carrinho, só estamos estudando em como adicionar o nome e a imagem :D 
Outra coisa que não lembramos é como arredondar o número, tentamos por .toFixed() e não foi hehe

Muito obrigada

2023-06-05 23:17 UTC, angelarf requested changes
Oie, acho q encontrei oq faltava para funcionar! 
Se juntar as correções do outro MR e desse aqui creio q teremos o site beeem funcional!

Qualquer coisa me chaam!

2023-06-05 23:17 UTC, angelarf commented on src/styles/Navbar.css
Oi Cinitia! Tudo bem? 

Novamente tive problemas com esse arquivo, dei uma olhada no git de vocês e ele está duplicado. 
Tente renomear o correto e remover o que não fizer sentido :)

2023-06-05 23:17 UTC, angelarf commented on src/styles/CartPage.css
Se esse arquivo estiver realmente vazio, sugiro que ele seja removido

2023-06-05 23:17 UTC, angelarf commented on src/contexts/UserContext.js
Como esse arquivo é o UserContext, sugiro que as funções e constantes dentro dele sigam o mesmo padrão de nomenclatura.
Ex:

cartContextProduct -> userContext
Ou então que renomeie o arquivo, para que as coisas se encaixem 😺

2023-06-05 23:17 UTC, angelarf commented on src/App.js
> +              <Route exact path="/cart" element={<Carrinho/>} />;
Não entendi muito bem pq ter vários componentes para a rota `/cart`. Acredito que o ideal seria ter uma só, que renderiza um componente principal. E esse componente poderia chamar os outros.

2023-06-05 23:17 UTC, angelarf commented on src/components/datails/ItemDetails.js
> +                    addToCart(cardItem.id, ammount, cardItem.preco);
```js
addToCart(cardItem.id, ammount, cardItem.preco, cardItem.nome, cardItem.imagem);
```
Não esqueça de passar os outros argumentos q a função addToCart precisa ;)

2023-06-05 23:17 UTC, angelarf commented on src/components/datails/ItemDetails.js
> +function ItemDetails({ cardItem, onClickToAdd }) {
essa função onClickToAdd não é utilizada e pode ser removida

2023-06-05 23:17 UTC, angelarf commented on src/contexts/CartContext.js
> +            cartItens.push({ ...itemDetails, qtd: qtd, preco: preco, nome: nome, imagem: imagem });
nao esqueça de adicionar o id!
```js
 cartItens.push({ id: id , qtd: qtd, preco: preco, nome: nome, imagem: imagem });

2023-06-05 23:17 UTC, angelarf commented on src/contexts/CartContext.js
> +        const itemDetails = productsDetails.find(product => product.id === id)
Como não estamos usando o mock, essa parte aqui pode ser removida. 
Os detalhes do item vc está recebendo por parametro dessa função ;)

2023-06-05 23:17 UTC, angelarf commented on src/contexts/CartContext.js
> +            cartItens.push({ ...itemDetails, qtd: qtd, preco: preco, nome: nome, imagem: imagem });
Creio que seja isso que está faltando para fazer a parte de criar ordem e salvar funcionar ;)

2023-06-06 18:47 UTC, crisCintia commented on src/styles/Navbar.css
Já fiz a exclusão do arquivo errado de todos os branchs

2023-06-06 18:48 UTC, crisCintia commented on src/styles/CartPage.css
Beleza, combinado :D

2023-06-06 19:51 UTC, crisCintia commented on src/App.js
> +              <Route exact path="/cart" element={<Carrinho/>} />;
Beleza, já exclui as rotas duplicadas do /cart :D

2023-06-06 19:54 UTC, crisCintia commented on src/components/datails/ItemDetails.js
> +                    addToCart(cardItem.id, ammount, cardItem.preco);
Ahh deu certo colocar a imagem e o nome, uhuuuul. Obrigadaa :D

2023-06-06 19:55 UTC, crisCintia commented on src/components/datails/ItemDetails.js
> +function ItemDetails({ cardItem, onClickToAdd }) {
Belezaa

2023-06-06 20:00 UTC, crisCintia commented on src/contexts/CartContext.js
> +        const itemDetails = productsDetails.find(product => product.id === id)
Huuum entendi, ficou melhor. Obrigadaa

2023-06-06 20:14 UTC, crisCintia commented on src/contexts/CartContext.js
> +            cartItens.push({ ...itemDetails, qtd: qtd, preco: preco, nome: nome, imagem: imagem });
Sim, foi isso mesmo! Ajustei e deu certo:

![image](https://github.com/alexscmachado/ecommerce_machado/assets/111471174/47308bc3-d5ca-4317-ab56-784b340141c0)

2023-06-06 20:25 UTC, crisCintia commented
@angelarf  já fizemos as atualizações dessa pull request e da anterior, deu tudo certo, muito obrigada pela ajudaa :D

2023-06-12 14:45 UTC, crisCintia commented
Desafio aprovado

2023-06-12 14:45 UTC, merged